Repository chili-publish/studio-ui, pull requests merged in 2024-04, with the labels that each got.

#137 [Fix][WRS-1658] Add PDF export (out of experimental)
  package.json
  src/components/navbar/downloadPanel/useDownload.tsx
  src/tests/navbar/useDownload.test.tsx
  src/utils/documentExportHelper.ts
  yarn.lock
Labels: No JIRA ticket, Ready for QA

#138 [Fix] Bump up SDK version
  package.json
  yarn.lock
Labels: No JIRA ticket, Ready for QA

#139 [Fix] Bump SDK to 1.8.1
  package.json
  yarn.lock
Labels: bug

#141 [Fix][WRS-1705] Fix hit area of switch component
  package.json
  src/App.tsx
  src/components/variablesComponents/BooleanVariable.tsx
  yarn.lock
Labels: Ready for QA

#143 [Fix][GRAFX-3215] Token refresh for dev mode
  README.md
  index.html
  package.json
  src/_dev-execution/bootstrap.ts
  src/_dev-execution/token-manager.ts
  src/components/variablesComponents/imageVariable/ImageVariable.tsx
  src/main.tsx
  vite.config.ts
  yarn.lock
Labels: Ready for QA
