Repository chili-publish/studio-ui, pull requests merged in 2024-11, with the labels that each got.

#221 [Feat][GRAFX-3857] Produce es module in addition to the "iife" for modern support
  README.md
  documentation/advanced-integration.md
  package.json
  src/_dev-execution/bootstrap.ts
  src/es-index.ts
  src/index.ts
  src/main.tsx
  vite.config.ts
Labels: Ready for QA

#219 [Feature] [WRS-1870] Use the label display value for variables
  __mocks__/mockVariables.ts
  src/components/variablesComponents/BooleanVariable.tsx
  src/components/variablesComponents/NumberVariable.tsx
  src/components/variablesComponents/TextVariable.tsx
  src/components/variablesComponents/dateVariable/DateVariable.tsx
  src/components/variablesComponents/imageVariable/ImageVariable.tsx
  src/components/variablesComponents/listVariable/ListVariable.tsx
  src/tests/VariablesComponents.test.tsx
  src/tests/VariablesList.test.tsx
  src/tests/mocks/mockVariables.ts
Labels: Ready for QA

#222 [Fix] Fix dev mode
  vite.config.ts
Labels: No JIRA ticket

#227 [Fix] [WRS-2127] Prevent shortcuts on inputs
  src/contexts/ShortcutManager/ShortcutProvider.tsx
Labels: Ready for QA

#229 [Fix] [WRS-2127] Select correct iframe in design mode
  package.json
  src/contexts/ShortcutManager/ShortcutProvider.tsx
  yarn.lock
Labels: Ready for QA

#234 [Fix] [WRS-2139] Fix timeline position
  package.json
  yarn.lock
Labels: Ready for QA

#236 [Release] Prep for 1.17
  package.json
  yarn.lock
Labels: No JIRA ticket, dependencies
