Repository chili-publish/studio-ui, pull requests merged in 2024-12, with the labels that each got.

#239 [Fix][WRS-2154] Use variable name as label as a fallback
  src/_dev-execution/bootstrap.ts
  src/components/variablesComponents/BooleanVariable.tsx
  src/components/variablesComponents/NumberVariable.tsx
  src/components/variablesComponents/TextVariable.tsx
  src/components/variablesComponents/dateVariable/DateVariable.tsx
  src/components/variablesComponents/imageVariable/ImageVariable.tsx
  src/components/variablesComponents/listVariable/ListVariable.tsx
  src/components/variablesComponents/listVariable/MobileListVariable.tsx
  src/tests/VariablesComponents.test.tsx
  src/tests/VariablesList.test.tsx
  src/tests/components/variablesComponents/booleanVariable/BooleanVariable.test.tsx
  src/tests/components/variablesComponents/dateVariable/DateVariable.test.tsx
  src/tests/components/variablesComponents/imageVariable/ImageVariable.test.tsx
  src/tests/components/variablesComponents/listVariable/ListVariable.test.tsx
  src/tests/components/variablesComponents/numberVariable/NumberVariable.test.tsx
  src/tests/components/variablesComponents/textVariable/TextVariable.test.tsx
  src/tests/mocks/mockVariables.ts
Labels: Ready for QA

#237 [Fix][WRS-1190] Don't execute SDK load event if document is not loaded
  src/DemoDocumentLoader.tsx
  src/MainContent.tsx
  src/StudioProjectLoader.tsx
  src/main.tsx
  src/tests/StudioProjectLoader.test.tsx
  src/types/types.ts
Labels: Ready for QA

#241 WRS-2133 - session store selected user interface
  src/StudioProjectLoader.tsx
  src/components/navbar/navbarItems/useUserInterfaceSelector.tsx
  src/components/navbar/studioNavbar/useStudioNavbar.tsx
  src/utils/constants.ts
Labels: Ready for QA

#232 [Fix] Update to newly shared components version
  package.json
  src/components/shared/Panel.styles.ts
  src/components/variables/VariablesPanel.styles.ts
  src/tests/components/variablesComponents/imageVariable/useMediaDetails.test.ts
  yarn.lock
Labels: No JIRA ticket, Ready for QA

#244 WRS-2173 - studio ui multi-page
  package.json
  src/MainContent.styles.tsx
  src/MainContent.tsx
  src/components/pagesPanel/Pages.styles.ts
  src/components/pagesPanel/Pages.tsx
  src/components/pagesPanel/PreviewCardBadge.tsx
  src/components/variables/MobileVariablesTray.tsx
  src/components/variables/VariablesPanel.styles.ts
  src/types/types.ts
  src/utils/constants.ts
  yarn.lock
Labels: Ready for QA

#248 [Fix] [WRS-2222] Update GSC version to fix DatePicker style
  package.json
  src/tests/components/dataSource/DataSourceModal.test.tsx
  yarn.lock
Labels: Ready for QA

#252 [Fix] Bump sdk version for realease
  package.json
  src/tests/VariablesComponents.test.tsx
  src/tests/components/variablesComponents/booleanVariable/BooleanVariable.test.tsx
  yarn.lock
Labels: No JIRA ticket

#250 [Fix][WRS-2174] Use project name as file name for outputs
  src/MainContent.tsx
  src/components/navbar/Navbar.tsx
  src/components/navbar/Navbar.types.ts
  src/components/navbar/studioNavbar/StudioNavbar.tsx
  src/components/navbar/studioNavbar/useStudioNavbar.tsx
  src/components/navbar/useDownloadPanel.ts
  src/tests/navbar/Navbar.test.tsx
Labels: Ready for QA

#246 [Fix][WRS-2123] Use DataSource API to operate with configured data source for project
  src/components/dataSource/useDataSource.ts
  src/tests/components/dataSource/DataSource.test.tsx
  src/tests/components/dataSource/DataSourceModal.test.tsx
  src/tests/components/dataSource/MobileDataSourceTray.test.tsx
Labels: Ready for QA

#251 [Feature] [WRS-2213] POC support kadanza
  src/App.styles.tsx
  src/MainContent.styles.tsx
  src/MainContent.tsx
  src/_dev-execution/bootstrap.ts
  src/components/animationTimeline/AnimationTimeline.tsx
  src/components/htmlRenderer/HtmlRenderer.style.tsx
  src/components/htmlRenderer/HtmlRenderer.tsx
  src/components/navbar/Navbar.tsx
  src/components/pagesPanel/Pages.tsx
  src/main.tsx
  src/types/types.ts
Labels: Ready for QA

#255 [Fix][WRS-2176] Show correct selection for data source when doing undo/redo
  package.json
  src/MainContent.tsx
  src/components/dataSource/useDataSource.ts
  src/tests/components/dataSource/DataSource.test.tsx
  src/tests/components/dataSource/DataSourceModal.test.tsx
  src/tests/components/dataSource/MobileDataSourceTray.test.tsx
  src/tests/components/dataSource/useDataSource.test.ts
  src/types/SDKError.ts
  src/utils/subscriber.ts
  yarn.lock
Labels: Ready for QA
