Repository chili-publish/studio-ui, pull requests merged in 2024-09, with the labels that each got.

#193 [Feature] Bump SDK version to 1.15.x
  package.json
  src/tests/LeftPanel.test.tsx
  yarn.lock
Labels: No JIRA ticket, Ready for QA

#195 [Fix] Add project id to output call
  .github/CODEOWNERS
  src/tests/LeftPanel.test.tsx
  src/utils/documentExportHelper.ts
Labels: Ready for QA

#196 [Fix] Change version to 1.15.1-rc.0 for hotfix release
  package.json
Labels: Ready for QA

#197 [FIX] [WRS-1961] Download modal background color changed to #FFFFFF
  src/components/navbar/downloadPanel/DownloadPanel.styles.tsx
Labels: Ready for QA

#199 [Bugfix] [WRS-1941] updated shared components
  package.json
  src/components/shared/StudioMobileDropdown/StudioMobileDropdown.styles.ts
Labels: Ready for QA

#203 [Fix] [NO-TICKET] Fix leftPanel flaky test
  src/tests/LeftPanel.test.tsx
Labels: No JIRA ticket

#200 [Fix] [WRS-2011] Set hand tool without document
  src/MainContent.tsx
  src/tests/LeftPanel.test.tsx
  src/tests/components/variablesComponents/imageVariable/useMediaDetails.test.ts
Labels: Ready for QA
