Repository chili-publish/studio-ui, pull requests merged in 2024-06, with the labels that each got.

#154 [Fix] [WRS-1764] Use userInterfaceId and outputSettings id in document download
  src/DemoDocumentLoader.tsx
  src/StudioProjectLoader.tsx
  src/components/navbar/downloadPanel/DownloadPanel.tsx
  src/components/navbar/downloadPanel/useDownload.tsx
  src/components/navbar/useNavbar.tsx
  src/main.tsx
  src/tests/StudioProjectLoader.test.tsx
  src/types/types.ts
  src/utils/documentExportHelper.ts
Labels: Ready for QA

#155 [Fix] Bump SDK version to 1.10.1
  package.json
  yarn.lock
Labels: No JIRA ticket

#156 [Fix] [WRS-1851] Revert to default user interface
  src/StudioProjectLoader.tsx
  src/types/types.ts
Labels: Ready for QA

#157 [Fix] [WRS-1854] Default to default user interface when id not provided
  src/StudioProjectLoader.tsx
Labels: Ready for QA

#161 [Fix][WRS-1861] Make refresh token action optional
  README.md
  documentation/advanced-integration.md
  src/App.tsx
  src/StudioProjectLoader.tsx
  src/main.tsx
  src/tests/StudioProjectLoader.test.tsx
  src/types/types.ts
  src/utils/documentExportHelper.ts
Labels: Ready for QA

#158 [Fix][WRS-1766] Reflect image frame value on variables updates
  src/App.tsx
  src/components/variablesComponents/imageVariable/ImageVariable.tsx
  src/components/variablesComponents/imageVariable/useMediaDetails.ts
  src/components/variablesComponents/imageVariable/usePreviewImageUrl.ts
  src/components/variablesComponents/useVariablesComponents.ts
  src/contexts/Subscriber.tsx
  src/contexts/VariablePanelContext.types.tsx
  src/core/hooks/useVariablesChange.ts
  src/tests/LeftPanel.test.tsx
  src/tests/VariablesComponents.test.tsx
  src/tests/VariablesList.test.tsx
  src/tests/components/variablesComponents/imageVariable/ImageVariable.test.tsx
  src/tests/components/variablesComponents/imageVariable/useMediaDetails.test.ts
  src/tests/components/variablesComponents/imageVariable/usePreviewImageUrl.test.ts
  src/tests/core/hooks/useVariablesChange.test.ts
  src/utils/subscriber.ts
Labels: Ready for QA

#164 [Fix] [WRS-1878] Fix number variable change adds 3 actions are added to undo stack
  src/components/variablesComponents/NumberVariable.tsx
  src/components/variablesComponents/VariablesComponents.types.ts
  src/components/variablesComponents/useVariablesComponents.ts
Labels: Ready for QA

#165 [Fix] Bump SDK version to 1.11.0
  package.json
  src/components/variablesComponents/imageVariable/useMediaDetails.ts
  yarn.lock
Labels: No JIRA ticket, Ready for QA

#167 [Fix][WRS-1821] Strict typings for connector's mappings
  src/components/variablesComponents/imageVariable/useMediaDetails.ts
Labels: Ready for QA

#163 [Feat][WRS-1761] Support "displayValues" for list variable items
  package.json
  src/App.tsx
  src/components/variables/VariablesList.tsx
  src/tests/VariablesList.test.tsx
  src/tests/mocks/mockVariables.ts
  yarn.lock
Labels: Ready for QA
