Repository chili-publish/studio-ui, pull requests merged in 2024-02, with the labels that each got.

#132 [Fix] Bump SDK version
  package.json
  yarn.lock
Labels: No JIRA ticket

#131 [Feature] [WRS-1556] Variable ImagePicker use resolvedMedia if available
  .github/actions/get-gh-app-installation-access-token/action.yml
  .github/actions/get-gh-app-jwt/action.yml
  .github/workflows/trigger-automated-tests.yml
  package.json
  src/components/variablesComponents/imageVariable/ImageVariable.tsx
  src/components/variablesComponents/useVariablesComponents.ts
  yarn.lock
Labels: Ready for QA

#133 [Fix] [WRS-1602] Media search improvements in Studio UI
  index.html
  src/components/itemBrowser/ItemBrowser.styles.tsx
  src/components/itemBrowser/ItemBrowser.tsx
  src/contexts/VariablePanelContext.tsx
  src/contexts/VariablePanelContext.types.tsx
Labels: Ready for QA

#136 [Fix] Bump SDK for hotfix 1.6.2
  package.json
  yarn.lock
Labels: No JIRA ticket, Ready for QA
