Repository chili-publish/studio-ui, pull requests merged in 2025-06, with the labels that each got.

#368 [Fix] Dependabot new additions
  yarn.lock
Labels: No JIRA ticket, Ready for QA

#369 [Feat][WRS-2414] Add support of translation for variable fields
  documentation/advanced-integration.md
  src/components/variables/MobileVariablesList.tsx
  src/components/variables/VariablesList.tsx
  src/core/hooks/useVariableTranslations.ts
  src/deprecated-loaders.tsx
  src/main.tsx
  src/store/index.ts
  src/store/reducers/appConfigReducer.ts
  src/tests/LeftPanel.test.tsx
  src/tests/LeftPanelLayout.test.tsx
  src/tests/MobileVariableTrayLayout.test.tsx
  src/tests/VariablesList.test.tsx
  src/tests/components/dataSource/MobileDataSourceTray.test.tsx
  src/tests/core/hooks/useVariableTranslations.test.ts
  src/tests/integration/VariableTranslation.test.tsx
  src/types/VariableTranslations.ts
  src/types/types.ts
Labels: Ready for QA

#375 [Feat][WRS-2519] Use variable name as fallback translation key
  src/core/hooks/useVariableTranslations.ts
  src/tests/core/hooks/useVariableTranslations.test.ts
Labels: Skip QA

#374 [Fix][WRS-2129] Add tooltip for navbar icon buttons
  package.json
  src/components/navbar/navbarItems/useNavbarUndoRedo.tsx
  src/components/navbar/navbarItems/useUserInterfaceSelector.tsx
  yarn.lock
Labels: Skip QA

#376 [WRS-2421] Close download modal when selected layout changes
  src/MainContent.tsx
  src/components/navbar/Navbar.tsx
  src/components/navbar/Navbar.types.ts
  src/components/navbar/studioNavbar/StudioNavbar.tsx
  src/components/navbar/useDownloadPanel.ts
  src/tests/navbar/Navbar.test.tsx
  src/tests/navbar/StudioNavbar.test.tsx
Labels: Ready for QA

#379 [Fix] add experimental warning on translations
  documentation/advanced-integration.md
Labels: No JIRA ticket
