Repository chili-publish/studio-ui, pull requests merged in 2025-02, with the labels that each got.

#273 [Fix] Update License
  LICENSE
Labels: documentation

#272 [Fix] sdk build version for release
  package.json
  yarn.lock
Labels: No JIRA ticket

#276 [Fix][WRS-2284] Use proper format for data source values in input
  package.json
  src/components/dataSource/useDataSource.ts
  yarn.lock
Labels: Ready for QA

#277 [Fix][WRS-2298] Read connector options from linked variable
  package.json
  src/components/pagesPanel/Pages.tsx
  src/components/variablesComponents/imageVariable/useMediaDetails.ts
  src/tests/components/variablesComponents/imageVariable/useMediaDetails.test.ts
  src/tests/utils/connectors.test.ts
  src/tests/utils/documentExportHelper.test.tsx
  src/types/OutputGenerationTypes.ts
  src/utils/connectors.ts
  yarn.lock
Labels: Ready for QA

#279 [Fix] Remove external styling
  src/App.tsx
  src/styles/GlobalStyle.ts
Labels: No JIRA ticket, Ready for QA

#265 [GRAFX-4110] change FF casing
  src/_dev-execution/bootstrap.ts
  src/components/layout-panels/leftPanel/LeftPanel.tsx
  src/components/variables/MobileVariablesTray.tsx
  src/tests/components/dataSource/MobileDataSourceTray.test.tsx
Labels: Ready for QA

#269 [Feature] [WRS-2247] Handle newer engine version in document
  src/MainContent.tsx
  src/components/load-document-error/LoadDocumentErrorDialog.styles.tsx
  src/components/load-document-error/LoadDocumentErrorDialog.tsx
  src/tests/LoadDocumentError.test.tsx
Labels: Ready for QA

#280 [Bump] New sdk
  package.json
  yarn.lock
Labels: No JIRA ticket, Ready for QA

#278 [Task][WRS-2283] allow end user to resize page size
  __mocks__/mockLayout.ts
  package.json
  src/MainContent.tsx
  src/components/LayoutPanel/Layout.styles.ts
  src/components/LayoutPanel/LayoutProperties.tsx
  src/components/LayoutPanel/types.ts
  src/components/LayoutPanel/useLayoutProperties.ts
  src/components/LayoutPanel/utils.ts
  src/components/layout-panels/leftPanel/LeftPanel.tsx
  src/components/variables/MobileVariablesTray.tsx
  src/tests/LeftPanel.test.tsx
  src/tests/LeftPanelLayout.test.tsx
  src/tests/MobileVariableTrayLayout.test.tsx
  src/tests/components/dataSource/MobileDataSourceTray.test.tsx
  yarn.lock
Labels: Ready for QA

#282 [Release] Prep for 1.20
  package.json
  yarn.lock
Labels: No JIRA ticket

#286 [Fix][WRS-2313] Add possibility to hide layout section and layout switcher
  src/MainContent.tsx
  src/_dev-execution/bootstrap.ts
  src/components/layout-panels/leftPanel/LeftPanel.tsx
  src/components/variables/MobileTrayHeader.tsx
  src/components/variables/MobileVariablesTray.tsx
  src/contexts/UiConfigContext.tsx
  src/tests/LayoutSectionUIOptions.test.tsx
  src/tests/LeftPanel.test.tsx
  src/tests/LeftPanelLayout.test.tsx
  src/tests/MobileVariableTrayLayout.test.tsx
  src/tests/components/dataSource/MobileDataSourceTray.test.tsx
  src/types/types.ts
Labels: Ready for QA

#285 [Fix] Theming documentation
  documentation/advanced-integration.md
Labels: No JIRA ticket

#289 [Fix] Revert version of the package
  package.json
Labels: No JIRA ticket

#291 [Fix] Use default options for LayoutSection
  src/MainContent.tsx
  src/_dev-execution/bootstrap.ts
Labels: No JIRA ticket, Ready for QA

#283 [Fix] [GRAFX-3252] Upgrade ts
  package.json
  yarn.lock
Labels: Ready for QA

#298 [Fix] Prepare for 1.21 release
  .github/workflows/production-build.yml
  package.json
  yarn.lock
Labels: No JIRA ticket, Ready for QA

#296 [Fix][WRS-2306] Run validation of the variables after data row change
  src/components/dataSource/useDataSource.ts
  src/components/variables/MobileVariablesList.tsx
  src/components/variables/VariablesList.tsx
Labels: Ready for QA
