Repository chili-publish/studio-ui, pull requests merged in 2025-09, with the labels that each got.

#417 [Fix][WRS-2653] Fix zoomtopage on multilayout view
  package.json
  src/MainContent.tsx
  src/tests/MainContent.test.tsx
  yarn.lock
Labels: Ready for QA

#407 [Feature][WRS-2586] Implement aspect ratio range with error state
  documentation/advanced-integration.md
  package.json
  src/_dev-execution/bootstrap.ts
  src/components/imagePanel/ImagePanel.tsx
  src/components/layoutProperties/Layout.styles.ts
  src/components/layoutProperties/LayoutProperties.tsx
  src/components/layoutProperties/LockedConstraintIcon.tsx
  src/components/layoutProperties/RangeConstraintErrorMessage.tsx
  src/components/layoutProperties/RangeConstraintIcon.tsx
  src/components/layoutProperties/useLayoutConstraintProportions.ts
  src/components/layoutProperties/useLayoutProperties.ts
  src/components/layoutProperties/util.ts
  src/components/variablesComponents/VariablesComponents.tsx
  src/tests/LayoutProperties/LayoutConstraintProportions.test.tsx
  src/tests/LayoutProperties/LeftPanelLayout.test.tsx
  src/tests/LayoutProperties/RangeConstraintErrorMessage.test.tsx
  src/tests/LayoutProperties/RangeConstraintIcon.test.tsx
  src/tests/components/layoutProperties/useLayoutProperties.test.ts
  src/types/UITranslations.ts
  src/utils/formatNumber.ts
  src/utils/precisionConfig.ts
  vite.config.ts
  yarn.lock
Labels: Ready for QA

#414 [Fix][WRS-2575] Handle media connector exception on preview calls
  package.json
  src/components/variablesComponents/imageVariable/ImageVariable.tsx
  src/components/variablesComponents/imageVariable/usePreviewImageUrl.ts
  src/setupTests.ts
  src/tests/LeftPanel.test.tsx
  src/tests/MobileTrayHeader.test.tsx
  src/tests/components/pagesPanel/Pages.test.tsx
  src/tests/components/variablesComponents/imageVariable/usePreviewImageUrl.test.ts
  src/tests/mocks/sdk.mock.ts
  src/types/UITranslations.ts
  yarn.lock
Labels: Skip QA

#419 Fix/restore bootstrap
  src/_dev-execution/bootstrap.ts
Labels: No JIRA ticket, Skip QA

#420 chore: restore download btn
  src/_dev-execution/bootstrap.ts
Labels: No JIRA ticket, Skip QA

#418 [Fix] Repurpose onProjectLoaded
  src/MainContent.tsx
  src/StudioProjectLoader.tsx
  src/_dev-execution/bootstrap.ts
  src/deprecated-loaders.tsx
  src/main.tsx
  src/tests/LayoutProperties/LeftPanelLayout.test.tsx
  src/tests/LoadDocumentError.test.tsx
  src/tests/MainContent.test.tsx
  src/tests/StudioProjectLoader.test.tsx
  src/tests/mocks/MockProjectConfig.ts
  src/tests/navbar/StudioNavbar.test.tsx
  src/types/types.ts
Labels: No JIRA ticket, Ready for QA

#422 chore: remove custom implementation of engine initialization
  src/_dev-execution/bootstrap.ts
Labels: No JIRA ticket, Skip QA

#423 [Fix] Prepare release 1.30.x
  package.json
  yarn.lock
Labels: No JIRA ticket, Ready for QA

#431 Hotfix/1.31.1
  .github/workflows/production-build.yml
  src/components/layoutProperties/RangeConstraintErrorMessage.tsx
Labels: No JIRA ticket, Ready for QA

#429 [Feature] Add integration callback tests
  __mocks__/mockVariables.ts
  src/tests/integration/IntegrationCallbacks.test.tsx
Labels: No JIRA ticket
