Repository chili-publish/studio-ui, pull requests merged in 2025-05, with the labels that each got.

#324 [TASK][WRS-2366] Data source & variables form builder in studio-ui
  documentation/advanced-integration.md
  src/MainContent.tsx
  src/components/dataSource/DataSource.tsx
  src/components/layout-panels/leftPanel/LeftPanel.tsx
  src/components/pagesPanel/Pages.styles.ts
  src/components/pagesPanel/Pages.tsx
  src/components/shared/Panel.styles.ts
  src/components/variables/MobileTrayHeader.tsx
  src/components/variables/MobileVariables.tsx
  src/components/variables/MobileVariablesTray.tsx
  src/components/variables/VariablesList.tsx
  src/core/hooks/useLeftPanelAndTrayVisibility.ts
  src/tests/LayoutSectionUIOptions.test.tsx
  src/tests/LeftPanel.test.tsx
  src/tests/MobileVariableTrayLayout.test.tsx
  src/tests/integration/FocusAndBlurVariables.test.tsx
  src/tests/integration/RequiredVariable.test.tsx
  src/tests/mocks/MockProjectConfig.ts
  src/tests/navbar/Navbar.test.tsx
  src/types/types.ts
Labels: Ready for QA

#340 [Feat][WRS-2413] Update prettier to latest
  .husky/pre-commit
  package.json
  src/MainContent.tsx
  src/core/hooks/useVariablesChange.ts
  src/store/reducers/mediaReducer.ts
  src/tests/LeftPanel.test.tsx
  src/tests/components/dataSource/DataSourceModal.test.tsx
  src/tests/components/dataSource/MobileDataSourceTray.test.tsx
  src/tests/integration/FocusAndBlurVariables.test.tsx
  src/types/types.ts
  src/utils/connectors.ts
  src/utils/precisionConfig.ts
  yarn.lock
Labels: Ready for QA

#344 [Fix] Bump SDK to 1.23.1 for hotfix
  __mocks__/mockVariables.ts
  package.json
  src/components/variablesComponents/VariablesComponents.tsx
  src/contexts/VariablePanelContext.tsx
  src/tests/components/variablesComponents/imageVariable/ImageVariable.test.tsx
  src/tests/components/variablesComponents/imageVariable/useVariablesConnector.test.ts
  src/tests/integration/StudioLoaderValidToken.test.tsx
  yarn.lock
Labels: No JIRA ticket, Ready for QA

#343 [Release] 1.23.5 SDK bump
  __mocks__/mockVariables.ts
  package.json
  src/components/variablesComponents/VariablesComponents.tsx
  src/contexts/VariablePanelContext.tsx
  src/tests/components/variablesComponents/imageVariable/ImageVariable.test.tsx
  src/tests/components/variablesComponents/imageVariable/useVariablesConnector.test.ts
  src/tests/integration/StudioLoaderValidToken.test.tsx
  yarn.lock
Labels: Ready for QA

#346 [Prep] Release 1.24 preparation
  package.json
  yarn.lock
Labels: No JIRA ticket

#348 [Release] 1.23.6
  src/_dev-execution/bootstrap.ts
  src/components/variablesComponents/dateVariable/DateVariableMobile.tsx
  src/components/variablesComponents/listVariable/ListVariable.tsx
  src/components/variablesComponents/listVariable/MobileListVariable.tsx
  src/components/variablesComponents/useVariablesComponents.ts
  src/main.tsx
  src/tests/VariablesComponents.test.tsx
  src/tests/mocks/sdk.mock.ts
  src/types/types.ts
Labels: No JIRA ticket, Ready for QA

#350 [Fix] #309 documentation issues
  documentation/advanced-integration.md
Labels: bug, documentation, No JIRA ticket

#339 WRS-2425 - cursor pointer for text area variable
  src/components/variablesComponents/MultiLineTextVariable.tsx
Labels: Ready for QA

#351 [Release] 1.24.0
  package.json
  yarn.lock
Labels: No JIRA ticket, Ready for QA

#337 [Feat][WRS-2441] Implement upload of assets using connectors for image variable
  README.md
  __mocks__/mockVariables.ts
  package.json
  src/_dev-execution/bootstrap.ts
  src/components/pagesPanel/Pages.tsx
  src/components/variablesComponents/VariablesComponents.tsx
  src/components/variablesComponents/VariablesComponents.types.ts
  src/components/variablesComponents/imageVariable/ImageVariable.tsx
  src/components/variablesComponents/imageVariable/usePreviewImageUrl.ts
  src/components/variablesComponents/imageVariable/useUploadAsset.ts
  src/components/variablesComponents/useVariablesComponents.ts
  src/components/variablesComponents/variablePlaceholder.util.ts
  src/contexts/VariablePanelContext.tsx
  src/tests/components/variablesComponents/imageVariable/ImageVariable.test.tsx
  src/tests/components/variablesComponents/imageVariable/usePreviewImageUrl.test.ts
  yarn.lock
Labels: Ready for QA

#352 Prep for 1.25 release
  package.json
  yarn.lock
Labels: No JIRA ticket, Ready for QA

#354 [Fix] Possibility to Skip AQA
  .github/workflows/trigger-automated-tests.yml
Labels: No JIRA ticket, Skip QA

#355 [Fix] [WRS-2430] Add Form builder logic test coverage
  src/tests/integration/FormBuilder.test.tsx
  src/tests/utils/formBuilder.test.ts
Labels: Ready for QA
