Repository chili-publish/studio-ui, pull requests merged in 2025-08, with the labels that each got.

#397 [Fix] Add missing translations keys
  documentation/advanced-integration.md
Labels: No JIRA ticket, Ready for QA

#400 [Fix] Prepare for 1.28
  package.json
  yarn.lock
Labels: No JIRA ticket, Skip QA

#403 [Fix] [WRS-2602] Fix scrollbar on mobile view
  package.json
  src/components/itemBrowser/ItemBrowser.tsx
  src/components/variables/MobileVariablesTray.tsx
  yarn.lock
Labels: Ready for QA
