Repository chili-publish/studio-ui, pull requests merged in 2025-07, with the labels that each got.

#381 Prepare 1.26.0 UAT release
  package.json
  yarn.lock
Labels: No JIRA ticket, Ready for QA, Skip QA

#380 [Feature] [WRS-2522] Add uiTranslations to studio ui config
  documentation/advanced-integration.md
  src/components/dataSource/DataSource.tsx
  src/components/dataSource/DataSourceInput.tsx
  src/components/dataSource/DataSourceModal.tsx
  src/components/layout-panels/leftPanel/AvailableLayouts.tsx
  src/components/layout-panels/leftPanel/LeftPanel.tsx
  src/components/layoutProperties/LayoutProperties.tsx
  src/components/layoutProperties/useLayoutProperties.ts
  src/components/navbar/downloadPanel/DownloadPanel.tsx
  src/components/navbar/navbarItems/useNavbarDownloadBtn.tsx
  src/components/variables/MobileVariables.tsx
  src/components/variables/MobileVariablesList.tsx
  src/components/variables/MobileVariablesTray.tsx
  src/components/variables/VariablesList.tsx
  src/core/hooks/useUITranslations.ts
  src/deprecated-loaders.tsx
  src/main.tsx
  src/store/reducers/appConfigReducer.ts
  src/tests/AppDigitalIntent.test.tsx
  src/tests/AppPrintIntent.test.tsx
  src/tests/DataRowNotifications.test.tsx
  src/tests/components/layoutProperties/useLayoutProperties.test.ts
  src/tests/core/hooks/useUITranslations.test.ts
  src/tests/integration/FormBuilder.test.tsx
  src/tests/integration/LayoutTranslations.test.tsx
  src/tests/integration/UITranslations.test.tsx
  src/types/UITranslations.ts
  src/types/types.ts
Labels: Ready for QA

#371 [Fix][WRS-2407] Use refreshed token during polling of output results
  src/StudioProjectLoader.tsx
  src/tests/integration/StudioLoaderExpiredToken.test.tsx
  src/tests/mocks/sdk.mock.ts
  src/tests/utils/documentExportHelper.test.tsx
  src/utils/documentExportHelper.ts
Labels: Ready for QA

#386 [Feat][GRAFX-4850] Correct default values for formbuilder
  __mocks__/mockUserinterface.ts
  src/StudioProjectLoader.tsx
  src/tests/StudioProjectLoader.test.tsx
  src/tests/integration/FormBuilder.test.tsx
  src/tests/integration/RequiredVariable.test.tsx
  src/tests/utils/formBuilder.test.ts
  src/types/types.ts
  src/utils/helpers.ts
Labels: Ready for QA

#389 [Feat][WRS-1875] Setup Sonar Cloud anylize
  .github/workflows/pr-build.yml
  jest.config.cjs
  sonar-project.properties
Labels: Skip QA

#394 [Feat][WRS-2563] Add UI translation for hamburger menu items
  src/components/navbar/navbarItems/useNavbarMenu.tsx
  src/components/navbar/studioNavbar/useStudioNavbar.tsx
  src/types/UITranslations.ts
Labels: Skip QA
